name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

env:
  GOOGLE_PROJECT_ID: konveyn2ai
  GOOGLE_REGION: us-central1

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    # Add permissions for OIDC token generation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          project_id: 'konveyn2ai'
          
      - name: Deploy to Cloud Run
        run: |
          chmod +x deployment/scripts/deploy-to-cloud-run.sh
          ./deployment/scripts/deploy-to-cloud-run.sh
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          INDEX_ID: ${{ secrets.INDEX_ID }}
          DEMO_TOKEN: ${{ vars.DEMO_TOKEN }}
          GOOGLE_CLOUD_PROJECT: 'konveyn2ai'
          BIGQUERY_DATASET_ID: 'semantic_gap_detector'
          
      - name: Validate Deployment
        run: |
          chmod +x deployment/tests/validate-deployment.sh
          ./deployment/tests/validate-deployment.sh
          
      - name: Run Integration Tests
        run: |
          chmod +x deployment/tests/test-real-integration.sh
          ./deployment/tests/test-real-integration.sh authenticated-only
