name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow Claude to make changes to files
      pull-requests: write  # Allow Claude to create/update PRs
      issues: write  # Allow Claude to update issues
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Configure Claude using claude_args (v1 format)
          claude_args: |
            --model claude-sonnet-4-20250514
            --max-turns 10
            --allowed-tools "Bash(make:*),Bash(pytest:*),Bash(python:*),Bash(pre-commit run:*),Bash(gh pr:*),Bash(gh issue:*),Bash(gh api:*),Bash(black:*)"

          # Use prompt parameter to provide project-specific guidance
          prompt: |
            This is a BigQuery AI Hackathon project. Key project guidelines:
            - Follow instructions in CLAUDE.md for project-specific protocols
            - Prefer editing existing files over creating new ones
            - Focus on functional implementation over mocks for demo readiness
            - Use make commands for BigQuery operations when needed
            - This is a Python/FastAPI backend with BigQuery integration

            When working with GitHub issues and PRs, use gh commands to fetch information.

          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

